#! /usr/bin/env python3

import sys

import cf_fetch as fetch

modules = {
    'fetch': fetch,
}

if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] not in modules.keys():
        pass
    modules[sys.argv[1]].parse_args(sys.argv[1:])
