#! /usr/bin/env python3

import sys

import cf_fetch as fetch

if __name__ == "__main__":
    if len(sys.argv) == 1:
        pass
    elif sys.argv[1] == 'fetch':
        fetch.parse_args(sys.argv[1:])
    else:
        pass
