#! /usr/bin/env python3

import sys
import os
import os.path
import requests
import lxml.html

def get_round():
    return os.path.basename(os.getcwd())

def get_problems_count(rnum):
    base_url = 'http://codeforces.com/contest/{rnum}/problems'
    url = base_url.format(**locals())
    r = requests.get(url).text
    doc = lxml.html.document_fromstring(r)
    return len(doc.xpath("//div[@class='problem-statement']"))


def get_tests(rnum):
    base_url = 'http://codeforces.com/contest/{rnum}/problem/{task}'
    problems_count = get_problems_count(rnum)
    for task in (chr(i) for i in range(ord('A'), ord('A') + problems_count)):
        print('Task {task}'.format(**locals()))
        url = base_url.format(**locals())
        doc = lxml.html.document_fromstring(requests.get(url).text)
        test_path = "//div[@class='sample-tests']/div[@class='sample-test']"
        input_elems = doc.xpath(test_path + "/div[@class='input']/pre")
        output_elems = doc.xpath(test_path + "/div[@class='output']/pre")

        nt = len(input_elems)

        input_text = []
        output_text = []
        for i in range(nt):
            input_text.append('\n'.join(input_elems[i].itertext()))
            output_text.append('\n'.join(output_elems[i].itertext()))

        for i in range(nt):
            with open('tests/{task}.{i}.in'.format(**locals()), 'w') as input_file:
                print(input_text[i], file=input_file)
            with open('tests/{task}.{i}.out'.format(**locals()), 'w') as output_file:
                print(output_text[i], file=output_file)

def get_problems(rnum):
    base_url = 'http://codeforces.com/contest/{rnum}/problems'
    url = base_url.format(**locals())
    r = requests.get(url).text
    with open('problems.html', 'w') as problems_file:
        print(r, file=problems_file)

if sys.argv[1] == 'tests':
    get_tests(get_round())
elif sys.argv[1] == 'round':
    print('Round #{}'.format(get_round()))
elif sys.argv[1] == 'problems-count':
    print('Problems count: {}'.format(get_problems_count(get_round())))
elif sys.argv[1] == 'problems':
    get_problems(get_round())
else:
    print('cf-test [tests|round|problems-count|problems]')
